import { PageHero } from '../../components/layout';
import { CTASection } from '../../components/sections';

export const metadata = {
  title: 'About HomeStake Capital | Mission, Model, and Principles',
  description:
    'Learn why HomeStake Capital is building a community-first holding company for home services, with a focus on operational discipline, transparency, and a more thoughtful ownership story.',
};

export default function AboutPage() {
  return (
    <>
      <PageHero eyebrow="About HomeStake Capital" title="We Believe the Public Should Have More Access to Own Real Businesses" description="HomeStake Capital is building a community-first holding company focused on essential home service businesses. The idea is to combine disciplined acquisitions and operational improvement with a more transparent ownership story and a more thoughtful path for owners considering a transition." primaryCta={{ href: '/waitlist', label: 'Join the Waitlist' }} secondaryCta={{ href: '/contact', label: 'Contact HomeStake' }} />
      <section className="section"><div className="container grid-2"><div><h2>Why We Are Building This</h2><p>Private equity has already shown that home services can be a compelling category for disciplined acquisitions. The businesses are essential. The market is fragmented. The operational upside can be real.</p><p>What has been less available is access, clarity, and alignment.</p><p>HomeStake exists to explore a different version of that model: one that treats ownership as something that can be more open, treats communication as part of the product, and treats sellers like people making a major life transition, not just counterparties in a process.</p></div><div className="card"><h3>What HomeStake Is</h3><p>HomeStake is being built as an acquisition and operating platform focused on home services. The model is centered on acquiring strong businesses, supporting them with better systems and shared services, and building long-term value over time.</p><p>This is not a passive-content brand pretending to be an operator. The operating model matters as much as the message.</p></div></div></section>
      <section className="section"><div className="container grid-2"><div className="card"><h2>Why Home Services</h2><p>Homes need heating, cooling, plumbing, electrical work, roofing, and maintenance regardless of what the market cycle is doing.</p><ul className="list-clean"><li>demand is tied to real household needs,</li><li>many businesses are still locally owned,</li><li>operational improvements can create meaningful value.</li></ul></div><div className="card"><h2>Our Point of View</h2><p>We believe the businesses that keep homes running should not feel completely out of reach to the public.</p><p>We believe local service businesses deserve buyers who care about continuity, not just spreadsheets.</p><p>We believe public participation should come with clearer communication, not more opacity.</p><p>And we believe a better ownership model only works if the operating discipline underneath it is real.</p></div></div></section>
      <section className="section"><div className="container grid-3">{[['Access with seriousness','Broader participation only works when the underwriting, governance, and communication are credible.'],['Plain-English transparency','If people are asked to trust the model, the model should be explainable.'],['Respect for owners','Selling a business is not just a transaction. It is a transition with emotional and operational consequences.'],['Operational discipline','The work is in the systems, reporting, integration, and execution.'],['Long-term stewardship','The goal is not performative disruption. The goal is to build something durable.'],['Who we serve','Future investors, business owners, and partners or advisors who can strengthen the platform through expertise, sourcing, credibility, and execution support.']].map(([title, body]) => <div className="card" key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></section>
      <section className="section"><div className="container grid-2"><div><h2>How We Intend to Build</h2><p>HomeStake is being designed around a straightforward idea: be clear about the category, be disciplined about acquisitions, build real operating support, and communicate progress without hype.</p><p>The long-term aim is a platform that pairs acquisitions with shared services, reporting discipline, and a stronger public narrative around who gets to participate.</p></div><div className="card"><h3>Building the team deliberately</h3><p>HomeStake is still in build mode. As the team, advisors, and operating partners are finalized, this page can expand to include founder background, advisor context, and execution depth.</p><p>For now, the focus is on making sure the strategy, structure, messaging, and operating logic are coherent before scale claims are made.</p></div></div></section>
      <section className="section"><div className="container card"><h2>What HomeStake Is Not</h2><ul className="list-clean"><li>Not a hype-driven finance brand</li><li>Not a promise of easy or guaranteed returns</li><li>Not anti-business or anti-scale</li><li>Not a generic roll-up story with softer packaging</li><li>Not a live offering unless and until formal materials say so</li></ul></div></section>
      <CTASection title="If the thesis makes sense to you, stay close to the build" body="Join the waitlist for launch updates and plain-English explainers, or reach out if you are a business owner, partner, or advisor who sees a fit." primary={{ href: '/waitlist', label: 'Join the Waitlist' }} secondary={{ href: '/contact', label: 'Contact HomeStake' }} />
    </>
  );
}
