import { PageHero } from '../../components/layout';
import { CTASection } from '../../components/sections';
import { site } from '../../lib/site';

export const metadata = {
  title: 'How HomeStake Works | Home Services Holding Company Model',
  alternates: {
    canonical: `${site.url}/how-it-works`
  },
  description:
    'See how HomeStake Capital plans to acquire, operate, and grow home service businesses through a disciplined, community-first platform built around transparency and long-term value.',
};

export default function HowItWorksPage() {
  return (
    <>
      <PageHero eyebrow="How HomeStake Works" title="A Simple Model, Built Around Real Operations" description="HomeStake Capital is building a platform designed to acquire, operate, and grow home service businesses over time. Here is the plain-English version of how the model is intended to work." primaryCta={{ href: '/waitlist', label: 'Join the Waitlist' }} secondaryCta={{ href: '/faq', label: 'Read the FAQ' }} />
      <section className="section"><div className="container grid-2"><div><h2>What This Is — and What It Is Not</h2><p>HomeStake is being built as a holding company and operating platform focused on essential home service businesses.</p><p>It is not just a brand story. It is not a promise of effortless passive income. And it is not a live offering page unless and until formal offering materials are in place.</p><p>The model depends on three things working together: capital formation, disciplined acquisitions, and operational improvement.</p></div><div className="card"><h3>The model in four steps</h3><div className="mock-list">{[['Build the capital base','HomeStake plans to raise capital through compliant channels and use the website, waitlist, and educational content to help people understand what the company is building.'],['Acquire strong home service businesses','The focus is on companies with real local trust, understandable economics, and room for improvement through better systems and support.'],['Improve operations across the portfolio','Instead of treating each company as fully standalone, HomeStake plans to support them through shared services like finance, marketing, procurement, reporting, and technology.'],['Build long-term value over time','As the platform matures, value is expected to come from stronger operations, better integration, and disciplined growth.']].map(([title, body]) => <div className="mock-row" key={title}><span><strong>{title}</strong><br />{body}</span></div>)}</div></div></div></section>
      <section className="section"><div className="container grid-3">{[['Why focus on home services','Home services are attractive because they are both essential and understandable. People need heating, cooling, plumbing, electrical work, roofing, and maintenance regardless of whether those services are exciting.'],['Why this category has attracted consolidators','Private equity firms have spent years consolidating home services because the category offers a familiar pattern: buy strong local businesses, improve operations, create scale advantages, and grow platform value over time.'],['The hub-and-spoke approach','A strong platform business in a local market can serve as the hub. Smaller tuck-in acquisitions around it can then add density, technician capacity, route efficiency, or adjacent service lines.']].map(([title, body]) => <div className="card" key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></section>
      <section className="section"><div className="container grid-3">{[['Stabilize','Retain key people, understand the business deeply, and make sure service quality does not break during transition.'],['Optimize','Tighten reporting, standardize key workflows, improve back-office systems, and identify the clearest margin or growth opportunities.'],['Grow','Add capacity, strengthen local execution, expand service opportunities where appropriate, and prepare for future tuck-ins or platform growth.']].map(([title, body]) => <div className="card" key={title}><span className="eyebrow">100-day playbook</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>
      <section className="section"><div className="container grid-2"><div className="card"><h2>What the capital is meant to build</h2><p>At a high level, HomeStake is being designed to use capital to support acquisitions, transition planning, operational improvements, and platform infrastructure.</p><p>The exact structure, offering mechanics, and capital allocation details will depend on legal structure, financing path, and finalized terms.</p></div><div className="card"><h2>What transparency should look like</h2><p>HomeStake&apos;s view is simple: if the public is invited into the story, the business should not be harder to follow than a traditional closed structure.</p><ul className="list-clean"><li>Understandable updates</li><li>Milestone communication</li><li>Plain-English explanations</li><li>Clearer reporting expectations over time</li></ul></div></div></section>
      <section className="section"><div className="container card"><span className="eyebrow">Where things stand today</span><h2>HomeStake is currently in build mode</h2><p>The immediate focus is on structure, compliance pathway, brand clarity, website and funnel readiness, and operating assumptions.</p><p>That means the current goal is not to overstate progress. The current goal is to make the model understandable and review-ready before launch.</p></div></section>
      <CTASection title="Follow the model before it goes live" body="Join the waitlist for launch updates, explainers, and early visibility into how HomeStake plans to build." primary={{ href: '/waitlist', label: 'Join the Waitlist' }} secondary={{ href: '/contact', label: 'Contact HomeStake' }} />
    </>
  );
}
