import { PageHero } from '../../components/layout';
import { CTASection, SellerForm } from '../../components/sections';

export const metadata = {
  title: 'For Business Owners | A Better Exit Than the Standard Roll-Up',
  description:
    'Thinking about selling your HVAC, plumbing, electrical, roofing, or other home service business? Explore a more thoughtful, legacy-conscious path with HomeStake Capital.',
};

export default function BusinessOwnersPage() {
  return (
    <>
      <PageHero eyebrow="For Business Owners" title="Sell Without Selling Out" description="If you are thinking about succession, retirement, or your next chapter, HomeStake Capital is being built to offer a more thoughtful alternative to the standard financial-buyer pitch." primaryCta={{ href: '#seller-form', label: 'Start a Confidential Conversation' }} secondaryCta={{ href: '/how-it-works', label: 'Learn How It Works' }} />
      <section className="section"><div className="container grid-2"><div><h2>Built for Owners Who Care What Happens Next</h2><p>For many founders, selling is not only about price. It is also about employees, customers, reputation, and whether the business they built will still feel recognizable after close.</p><p>HomeStake is being positioned around a different conversation: continuity where possible, respect for local trust, operational support after close, and a more human transition story.</p></div><div className="card"><p className="notice">Early conversations are meant to be discreet, practical, and focused on fit.</p></div></div></section>
      <section className="section"><div className="container grid-4">{[['Protect what you built','Your local reputation, customer trust, and team history matter.'],['Transition with support','The goal is not a chaotic handoff. The goal is a structured transition.'],['Stay involved if it makes sense','Depending on the situation and deal structure, continued involvement may be part of the transition plan.'],['Join a stronger platform','Shared services and better systems can help a good business become more durable over time.']].map(([title, body]) => <div className="card" key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></section>
      <section className="section"><div className="container card"><span className="eyebrow">HomeStake vs traditional PE</span><h2>A Different Conversation Than the Standard Roll-Up Pitch</h2><table className="compare"><thead><tr><th>Area</th><th>HomeStake</th><th>Traditional PE framing</th></tr></thead><tbody>{[['Approach to owners','Emphasizes transition, alignment, and long-term stewardship','Often leads with price, structure, and speed'],['Approach to legacy','Treats reputation and continuity as real assets','May prioritize centralization first'],['Approach to communication','Aims to be plainspoken and transparent about process','Can feel heavily financial or impersonal'],['Approach to post-close support','Built around operational improvement and shared services','Varies significantly by buyer']].map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></section>
      <section className="section"><div className="container grid-2"><div className="card"><h2>What Makes a Strong Fit</h2><ul className="list-clean"><li>HVAC, plumbing, electrical, roofing, landscaping, pest control, or related service categories</li><li>Strong customer reputation and local presence</li><li>Healthy or improvable margins</li><li>Repeat business, maintenance revenue, or recurring customer relationships</li><li>Owner approaching succession, retirement, or transition</li><li>A management bench or transition plan that can support continuity</li></ul></div><div className="card"><h2>What the process can look like</h2><div className="mock-list">{[['Initial conversation','A discreet first discussion about your business, timing, and goals.'],['Fit review','A high-level review to determine whether the company appears to fit HomeStake\'s target profile.'],['Deeper diligence and structure discussion','If there is mutual interest, the conversation moves into more detail around business quality, transition needs, and possible deal structure.'],['Thoughtful transition planning','If a transaction moves forward, the focus shifts to continuity, communication, and operational handoff.']].map(([title, body]) => <div className="mock-row" key={title}><span><strong>{title}</strong><br />{body}</span></div>)}</div></div></div></section>
      <section className="section"><div className="container grid-2"><div><h2>What We Believe Matters in a Transition</h2><p>A serious transition should improve the business without needlessly damaging what made it valuable in the first place.</p><ul className="list-clean"><li>strong local brand equity,</li><li>key people,</li><li>service standards,</li><li>customer relationships.</li></ul><p>We are not promising that nothing changes. We are saying the transition should be thoughtful.</p></div><div className="card"><h3>Discreet by default</h3><p>Many owners want to explore options before they are ready to talk broadly with staff, customers, or competitors. That is reasonable.</p><p>HomeStake&apos;s seller path should be designed to start with discretion, practical fit assessment, and a low-drama first conversation.</p></div></div></section>
      <section className="section" id="seller-form"><div className="container grid-2"><div><h2>Thinking about the next chapter?</h2><p>If you want to explore what a more aligned transition could look like, start with a confidential conversation.</p></div><SellerForm /></div></section>
      <CTASection title="Thinking about the next chapter?" body="If you want to explore what a more aligned transition could look like, start with a confidential conversation." primary={{ href: '#seller-form', label: 'Start a Confidential Conversation' }} secondary={{ href: '/contact', label: 'Contact HomeStake' }} />
    </>
  );
}
